name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTE4ZjY0YzAtMjIzYy00ZGYwLWI2ZDYtMWYyYWMxOTk0MTMwIiwidGVuYW50X2lkIjoiNzc4ZDgzNGViNGQzZDJlZGVjYmUxYzlkNWQyMWU4OGQyOTY0NmE5OGExOGFjMGIwMTM4NWRiMDMxZTI3MzdkYSIsImludGVybmFsX3NlY3JldCI6IjRhYzNjZTgzLWU0NjMtNDQ4ZC04OGFlLTcwNTRkYzkyNzc0YSJ9.LwMbbQ7eZ2Zic-sKUNIzNpghO19FnMM1VkIYzzF_WyE"